insert into Movies values (NEWID(), 'The Piano', 'Romantic', '1993-08-23')
insert into Movies values (NEWID(), 'Forrest Gump', 'Crima', '1994-02-25')
insert into Movies values (NEWID(), 'Se7en', 'Comedie', '1995-04-12')
insert into Movies values (NEWID(), 'Titanic', 'Romantic', '1997-05-14')
insert into Movies values (NEWID(), 'Gladiator', 'Actiune', '2000-07-09')
insert into Movies values (NEWID(), 'The Lord of the Rings: The Fellowship of the Ring ', 'Fantastic', '2001-08-23')
insert into Movies values (NEWID(), 'The Lord of the Rings: The Two Towers ', 'Fantastic', '2002-02-25')
insert into Movies values (NEWID(), 'Pirates of the Caribbean', 'Aventura', '2006-04-12')
insert into Movies values (NEWID(), 'Avatar', 'Aventura, SF', '2009-05-14')
insert into Movies values (NEWID(), 'Jurassic Park', 'Actiune', '1993-07-09')